default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "db" } %>
  username: postgres
  password: dev

development:
  <<: *default
  database: timescale_app_development

test:
  <<: *default
  database: timescale_app_test

production:
  <<: *default
  database: timescale_app_production
